/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.util.ArrayList;
import javax.swing.JFrame;
import paquete.Cliente;
import productos.modelos.Categoria;
import productos.modelos.ModeloComboCategorias;
import usuarios.modelos.Empleado;
import usuarios.modelos.ModeloTablaUsuarios;
import usuarios.modelos.Usuario;

/**
 *
 * @author root
 */
public class VentanaProductos extends JFrame {

    /**
     * Creates new form Productos
     */
    public VentanaProductos() {
        initComponents();
        this.setLocationRelativeTo(null);
        ModeloComboCategorias mcc = new ModeloComboCategorias();
        this.comboCategorias.setModel(mcc);
        Categoria c = Categoria.PLATO_PRINCIPAL;
        ((ModeloComboCategorias)this.comboCategorias.getModel()).asignarCategoria(c);
        
        ArrayList<Usuario> usuarios = new ArrayList<>();
        usuarios.add(new Cliente("correo1", "clave1", "apellidos1", "nombres1"));
        usuarios.add(new Cliente("correo2", "clave2", "apellidos2", "nombres2"));
        usuarios.add(new Empleado("correo3", "clave3", "apellidos3", "nombres3"));
        ModeloTablaUsuarios mtu = new ModeloTablaUsuarios(usuarios);
        tablaUsuarios.setModel(mtu);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo1 = new javax.swing.ButtonGroup();
        cbHabilitado = new javax.swing.JCheckBox();
        Aceptar = new javax.swing.JButton();
        txtDescripcion = new javax.swing.JTextField();
        rbValor1 = new javax.swing.JRadioButton();
        rbValor2 = new javax.swing.JRadioButton();
        rbValor3 = new javax.swing.JRadioButton();
        comboCategorias = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Productos (JFrame)");
        setResizable(false);

        cbHabilitado.setSelected(true);
        cbHabilitado.setText("Habilitado");

        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        grupo1.add(rbValor1);
        rbValor1.setSelected(true);
        rbValor1.setText("Valor1");

        grupo1.add(rbValor2);
        rbValor2.setText("Valor2");

        grupo1.add(rbValor3);
        rbValor3.setText("Valor3");

        comboCategorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaUsuarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Aceptar)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbHabilitado)
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(comboCategorias, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbValor1)
                                .addGap(18, 18, 18)
                                .addComponent(rbValor2)))
                        .addGap(18, 18, 18)
                        .addComponent(rbValor3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(87, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbHabilitado))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbValor1)
                    .addComponent(rbValor2)
                    .addComponent(rbValor3))
                .addGap(18, 18, 18)
                .addComponent(comboCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(Aceptar))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        System.out.println(this.cbHabilitado.isSelected());
        System.out.println(this.txtDescripcion.getText());
        System.out.println(((ModeloComboCategorias)this.comboCategorias.getModel()).verCategoria());
    }//GEN-LAST:event_AceptarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JCheckBox cbHabilitado;
    private javax.swing.JComboBox<String> comboCategorias;
    private javax.swing.ButtonGroup grupo1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbValor1;
    private javax.swing.JRadioButton rbValor2;
    private javax.swing.JRadioButton rbValor3;
    private javax.swing.JTable tablaUsuarios;
    private javax.swing.JTextField txtDescripcion;
    // End of variables declaration//GEN-END:variables
}
